wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.6
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1704722467.132815
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 23
      4: 3.8.6
      5: 0.16.1
      8:
      - 1
      - 5
      13: linux-x86_64
